- alias: 'Fans Off in Morning'
  trigger:
    - platform: time
      hours: 9
      minutes: 00
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: switch.turn_off
    entity_id: switch.fans

