homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !env_var HOME_LAT
  longitude: !env_var HOME_LON
  # C for Celcius, F for Fahrenheit
  #temperature_unit: F
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  elevation: 86


http:
  api_password: !env_var API_PASSWORD

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time.
history:

# Show links to resources in log and frontend
#introduction:

# Checks for available updates
updater:

# Track the sun
sun:

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:


####################################################
################    Connected  #####################
####################################################
ifttt:
  key: !env_var IFTT_KEY

wink:
  email: !env_var WINK_EMAIL
  password: !env_var WINK_PASSWORD
  client_id: !env_var WINK_CLIENT_ID
  client_secret: !env_var WINK_CLIENT_SECRET

wemo:

####################################################
################     Tracking  #####################
####################################################

# device_tracker:
#   platform: nmap_tracker
#   hosts: 192.168.1.1/24
#   home_interval: 10

####################################################
################    Automation #####################
####################################################

# automation:
#   - alias: 'Lights on before sunrise'
#     trigger:
#       platform: sun
#       event: sunrise
#       offset: "-00:45:00"
#     action:
#       service: scene.turn_on
#       entity_id: scene.day


automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors


