- alias: 'Accent Off in Morning'
  trigger:
    platform: sun
    event: sunrise
    offset: '+01:00:00'
  action:
    service: switch.off
    entity_id: switch.bathroom_accent
  action:
    service: switch.off
    entity_id: switch.kitchen_cabinet_lights

- alias: 'Accent On at Night'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  action:
    service: scene.turn_off
    entity_id: scene.accent