# - alias: "One lights on if no one home before sunset"
#   trigger:
#     platform: numeric_state
#     entity_id: sun.sun
#     value_template: "{{ state.attributes.elevation }}"
#     below: -4.0
#   condition:
#     condition: state
#     entity_id: group.people
#     state: not_home
#   action:
#     service: scene.turn_on
#     entity_id: group.not_home_night

- alias: Start fading lights as sunsets
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
      below: -4.0
  action:
    service: python_script.fade_up.against_sunset
      data_template:
        entity_id: group.all_lights
        ideal_start_angle_of_sun: -4
        current_angle_of_sun: "{{ states.sun.sun.attributes.azimuth }}"
        time_of_sunset: "{{ as_timestamp(states.sun.sun.attributes.next_setting) }}"
        end_level_pct: 80
        start_level_pct: 0
        step_in_level_pct: 2
        time_now: "{{ as_timestamp(now()) }}"