- alias: "test"
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: python_script.fade_in
      data_template:
        entity_id: light.kitchen
        ideal_start_angle_of_sun: -4
        current_angle_of_sun: -2
        time_of_sunset: "{{ as_timestamp(now()) }}"
        end_level_pct: 100
        start_level_pct: 0
        step_in_level_pct: 2
        time_now: "{{ as_timestamp(now()) }}"

- alias: "test2"
  trigger:
    - platform: time
      at: '07:00:00'
  action:
    - service: python_script.fade_up_against_sunset
      data_template:
        entity_id: group.all_lights
        ideal_start_angle_of_sun: -4
        current_angle_of_sun: "{{ states.sun.sun.attributes.azimuth }}"
        time_of_sunset: "{{ as_timestamp(states.sun.sun.attributes.next_setting) }}"
        end_level_pct: 100
        start_level_pct: 0
        step_in_level_pct: 2
        time_now: "{{ as_timestamp(now()) }}"

- alias: "Wake Up"
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.holiday_override
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.wake

- alias: "Morning"
  trigger:
    - platform: time
      at: '07:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.holiday_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.override_light_automation
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.morning

- alias: "Off to Work"
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.holiday_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.override_light_automation
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.not_home_day
