- alias: "Wake Up"
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: scene.turn_on
    entity_id: scene.wake

- alias: "Morning"
  trigger:
    - platform: time
      at: '07:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: scene.turn_on
    entity_id: scene.morning


- alias: "Off to Work"
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: scene.turn_on
    entity_id: scene.not_home_day


- alias: "Late Evening"
  trigger:
    - platform: time
      at: '19:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: scene.turn_on
    entity_id: scene.late_evening
