- alias: "Wake Up"
  trigger:
    - platform: time
      hours: 7
      minutes: 00
      seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.holiday_override
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.wake

- alias: "Morning"
  trigger:
    - platform: time
      hours: 7:45
      minutes: 00
      seconds: 0
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.holiday_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.override_light_automation
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.morning
