- alias: "Wake Up"
  trigger:
    - platform: time
      at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: scene.turn_on
    entity_id: scene.wake

- alias: "Morning"
  trigger:
    - platform: time
      at: '07:45:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: scene.turn_on
    entity_id: scene.morning

- alias: "Off to Work"
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: scene.turn_on
    entity_id: scene.not_home_day

# All days shared lights faded up against sun.

- alias: "Late Evening"
  trigger:
    - platform: time
      at: '21:15:00'
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: scene.turn_on
      entity_id: scene.late_evening
    - service: switch.turn_on
      entity_id:
