- alias: 'Lights on in the Morning'
  trigger:
    - platform: time
      hours: 9
      minutes: 00
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: scene.turn_on
    entity_id: scene.morning

- alias: 'Lights off during the weekend'
  trigger:
    - platform: time
      hours: 10
      minutes: 00
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: scene.turn_on
    entity_id: scene.lights_off

- alias: 'Lightings On Weekend'
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: scene.turn_on
    entity_id: scene.early_evening

- alias: 'Late Evening'
  trigger:
    - platform: time
      hours: 20
      minutes: 45
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: scene.turn_on
    entity_id: scene.late_evening

- alias: 'Night Lighting'
  trigger:
    - platform: time
      hours: 22
      minutes: 45
      seconds: 0
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: scene.turn_on
    entity_id: scene.night